import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <main className={inter.className}>
        {/* Main Navbar Component */}
        <Navbar />
        <body className="max-w-[2520px] mx-auto xl:px-20 md:px-10 sm:px-2 px-4">
          {children}
        </body>

        {/* footer */}
      </main>
    </html>
  );
}
